# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:

- {name: 'Notes', folder: 'pages', file: 'notes.html'}
- {name: 'Code', folder: 'pages', file: 'code.html'}
- {name: 'Video', folder: 'pages', file: 'video.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/weary_youth'}
- {icon: 'envelope', link: 'mailto:jcorneille107@gmail.com'}
- {icon: 'github', link: 'https://github.com/josh-corneille'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
